Giveaways cleanup
Curiosity-org/Gipsy pull request #217
Opened 2023-06-16 16:32 UTC by ZRunner

This PR is a large rework of the giveaways plugin:
- migrate from reactions to buttons
- migrate from text commands to slash commands only (with autocompletion)
- add the `Gunibot.get_command_mention` method, and subsequent methods
- remove the `giveaways_emojis` config value (because we don't use emojis anymore)
- remove the confusing stopped VS ended giveaway state - now they are either running or ended
- improve the generated embeds, notably with some better formulations
- refactor the code for some massive cleanup, notably Python linting-wise and SQL queries

What should have been added but was canceled due to technical difficulties:
- get giveaways description different than the name (missing database migration system)
- remove the "running" column from the database table (missing database migration system)

2023-06-16 20:06 UTC, ascpial requested changes
La chaîne de l'embed d'information n'est pas correctement traduite, il manque la traduction dans le fichier `fr.yaml`.

![image](https://github.com/Curiosity-org/Gipsy/assets/72463129/a3cb6afe-af7f-45cb-8d5b-9dd934f6ac77)

2023-06-16 20:07 UTC, ascpial commented
Il pourrait aussi être intéressant d'implémenter l'autocomplétion pour les giveaway dans les différentes commandes pour simplifier la recherche.

2023-06-16 20:08 UTC, ascpial requested changes
Avec suffisamment peu de participants, il est possible que le même participant soit tiré plusieurs fois.

![image](https://github.com/Curiosity-org/Gipsy/assets/72463129/aa40bc23-b96d-45e8-b674-e8448685c637)

2023-06-16 20:40 UTC, ZRunner commented
Corrigé, merci

2023-06-16 20:48 UTC, ascpial requested changes

2023-06-16 20:48 UTC, ascpial commented on plugins/giveaways/giveaways.py
> +        ends_at: Optional[datetime.datetime] = None,
Cette valeur est-elle vraiment optionnelle ?

La command / ne permet pas de ne pas remplir cette valeur.

2023-06-16 20:48 UTC, ascpial commented on plugins/giveaways/giveaways.py
>          [p]giveaway info Minecraft account"""
L'indication de préfixe est-elle toujours d'actualité, sachant que la commande 
est désormais accessible uniquement par les commandes / ?

Cette remarque doit être applicable à d'autres endroits du bot.

2023-06-16 20:48 UTC, ascpial commented on plugins/giveaways/giveaways.py
> +    async def gw_info_autocomplete(self, interaction: discord.Interaction, current: str):
Cette redondance est-elle nécessaire, sachant qu'il est possible d'assigner à chacune des commandes la même fonction d'autocomplétion ?

2023-06-17 18:24 UTC, ascpial approved these changes
Testé et approuvé

2023-06-17 19:09 UTC, merged