🔥 >emove twitter from the rss plugin
Curiosity-org/Gipsy pull request #242
Opened 2023-08-30 16:58 UTC by ascpial

Closes #235.

2023-08-30 17:44 UTC, Aeris1One requested changes
Review rapide, semble correct. À tester de manière extensive.

Est-ce que tu pourrais également fix l'erreur PyLint ? 
Elle semble dûe au fait que le setup.py gère de façon incorrecte l'acceptation/le refus (un coup sur deux il vérifie que la réponse est un refus, un coup sur deux que c'est une acceptation, elle devrait faire les deux)

2023-08-31 07:55 UTC, ascpial commented
Comme indiqué par l'input, la valeur sélectionnée par défaut est l'activation de la boucle RSS `(Y/n)`. Il me semble donc approprié de vérifier que la valeur n'est pas négative.

2023-08-31 09:47 UTC, Aeris1One submitted a review, later dismissed

2023-08-31 09:52 UTC, ascpial reviewed
Ça me paraît globalement bon, je vais tester les modifications d'Aeris de mon côté.

2023-08-31 09:52 UTC, ascpial commented on setup.py
> +from core.config import ask_user
Ne serais-t-il pas plus censé d'accéder à la fonction avec `config.ask_user` ?

2023-08-31 09:57 UTC, Aeris1One commented on setup.py
> +from core.config import ask_user
J'ai préféré l'importer directement pour éviter de perdre d'éventuels contributeurs en se disant que si elle provient de config. c'est qu'elle modifie la config en arrière-plan alors que non. C'est plus simple également d'après moi.

2023-08-31 10:03 UTC, Aeris1One approved these changes

2023-11-02 16:47 UTC, ZRunner approved these changes
LGTM

2023-11-02 20:48 UTC, merged